export const INDUSTRIES = [
  "Healthcare & Medical",
  "Dental",
  "Legal Services",
  "Real Estate",
  "Home Services (HVAC, Plumbing, Electrical)",
  "Auto Repair & Dealerships",
  "Insurance",
  "Financial Services",
  "SaaS & Technology",
  "E-commerce & Retail",
  "Restaurants & Hospitality",
  "Fitness & Wellness",
  "Education & Tutoring",
  "Marketing & Advertising",
  "Accounting & Tax",
  "Construction",
  "Cleaning Services",
  "Pet Services",
  "Photography & Videography",
  "Consulting",
  "Other",
] as const;

export const TIMEZONES = [
  "America/New_York",
  "America/Chicago",
  "America/Denver",
  "America/Los_Angeles",
  "America/Phoenix",
  "America/Anchorage",
  "Pacific/Honolulu",
  "America/Toronto",
  "America/Vancouver",
  "Europe/London",
  "Europe/Paris",
  "Europe/Berlin",
  "Asia/Tokyo",
  "Asia/Shanghai",
  "Australia/Sydney",
] as const;
